# Generated by Django 6.0 on 2025-12-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_moto_observaciones_moto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='placa',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
